style: Advertise underscore_separation for function names
UCL/rsd-engineeringcourse pull request #265
Opened 2024-11-29 16:05 UTC by zhaohany

This PR updates the naming conventions section to promote the use of `underscore_separation` for function names, in alignment with [[PEP 8](https://pep8.org/)](https://pep8.org/) guidelines.

Fixes issue: [[UCL/rsd-engineeringcourse#263](https://github.com/UCL/rsd-engineeringcourse/issues/263)](https://github.com/UCL/rsd-engineeringcourse/issues/263)

2024-11-29 23:38 UTC, Saransh-cpp requested changes
Thanks, @zhaohany! Just a minor suggestion -

2024-11-29 23:38 UTC, Saransh-cpp commented on ch05construction/02conventions.ipynb.py
> +# [Camel case](https://en.wikipedia.org/wiki/Camel_case) is used for class names in the following example, while function and variable names follow snake_case (underscore_separation). This convention
```suggestion
# [UpperCamel case](https://en.wikipedia.org/wiki/Camel_case) is used for class names in the following example, while function and variable names follow snake_case (underscore_separation). This convention is widely used in the Python community, as stated in [PEP 8](https://pep8.org/).
```

2024-11-29 23:48 UTC, Saransh-cpp approved these changes
Thanks for picking this up!

2024-11-30 15:04 UTC, zhaohany commented
Thank you @Saransh-cpp, seems the build failed due to a key, I see similar PR before can skip this steps but I do not have access to trigger the build, would you please help merge this? Thank you.

2024-12-02 09:08 UTC, Saransh-cpp requested changes
Hi, @zhaohany! Please don't worry about the CI. The CI is failing because this PR is from a fork. A minor comment that I missed before -

2025-01-10 19:56 UTC, merged

2025-01-10 19:56 UTC, Saransh-cpp commented
Thanks for working on this, @zhaohany!